[package]
name = "fluxterm-openai"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
fluxterm-logging = { workspace = true }

log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
reqwest = { workspace = true }
