name: Release

run-name: "Version ${{ inputs.tag_name }}"

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "App version (e.g. 0.1.0-rc.1)"
        required: true
      release_name:
        description: "The name of the release."
        required: false
        default: Version

jobs:
  release:
    permissions:
      contents: write
    uses: ./.github/workflows/release-build.yml
    with:
      tag_name: ${{ inputs.tag_name }}
      release_name: ${{ inputs.release_name }}
      release_target: private
    secrets: inherit
